name: get secrets
description: get random secrets
inputs:
  SECRET_PARAM:
    description: needed to retrieve our secrets
    required: true
outputs:
  secrets:
    value: ${{ steps.secrets.outputs }}
    description: the gathered external secrets
runs:
  using: composite
  steps:
    - id: secrets
      name: get secrets
      uses: ./.github/actions/simulate_external
      with:
        credentials: ${{ inputs.SECRET_PARAM }}
