name: get secrets
description: get random secrets
inputs:
  SECRET_PARAM:
    description: needed to retrieve our secrets
    required: true
runs:
  using: composite
  steps:
    - id: secrets
      name: get secrets
      uses: ./.github/actions/simulate_external
      with:
        credentials: ${{ inputs.SECRET_PARAM }}
    - name: publish to environment
      shell: bash
      run: |
        echo SECRET_GEN1="${{ steps.secrets.outputs.secret1 }}" >> $GITHUB_ENV
        echo SECRET_GEN2="${{ steps.secrets.outputs.secret2 }}" >> $GITHUB_ENV

