name: simulated external secret provider
description: simulates GCP secret gatherer
inputs:
  secrets:
    description: |-
      Comma-separated or newline-separated list of secrets to fetch. Secrets
      must be of the format <project>/<secret> or <project>/<secret>/<version>.
    required: true
  credentials:
    description: |-
      Service account key to use for authentication. This should be the JSON
      formatted private key which can be exported from the Cloud Console. The
      value can be raw or base64-encoded.
    required: false

branding:
  icon: 'lock'
  color: 'blue'

runs:
  using: composite
  steps:
    - name: get them
      shell: bash
      run: |
        output1=${{ inputs.credentials }}
        echo "::set-output name=secret1::$output1"
        echo "::set-output name=secret2::topsecure"