name: update service version
on:
  workflow_dispatch:
    inputs:
      service:
        description: the service name
        required: false
      version:
        description: the service version
        required: false

jobs:
  modify_chart:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo "${{ inputs.version }}" > version-${{ inputs.service }}.txt
          git commit -a -m "${{ inputs.service }} version => ${{ inputs.version }}"
          git push
