name: update service version
on:
  workflow_call:
    inputs:
      service:
        description: the service name
        required: false
        type: string
        default: ""
      version:
        description: the service version
        required: false
        type: string
        default: "1.0.0"

  workflow_dispatch:
    inputs:
      service:
        description: the service name
        required: false
        default: ""
      version:
        description: the service version
        required: false
        default: "1.0.0"

jobs:
  modify_chart:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo "${{ inputs.version }}" > version-${{ inputs.service }}.txt
          git commit -a -m "${{ inputs.service }} version => ${{ inputs.version }}"
          git push
